Repository Idda-Dev/Idda_FE, pull requests merged in 2025-08, with the labels that each got.

#4 [feat/newpostitem] 게시글 ui 완료
  src/Router.jsx
  src/features/PostItem/assets/BackIcon.png
  src/features/PostItem/assets/CommentIcon.png
  src/features/PostItem/assets/LikedIcon.png
  src/features/PostItem/assets/ModalIcon.png
  src/features/PostItem/assets/PencilIcon.png
  src/features/PostItem/assets/PostImage.png
  src/features/PostItem/assets/ProfileIcon.png
  src/features/PostItem/assets/PurpleCommunityIcon.png
  src/features/PostItem/components/CommentInput.jsx
  src/features/PostItem/components/CommentList.jsx
  src/features/PostItem/components/CommentListItem.jsx
  src/features/PostItem/components/Comments.jsx
  src/features/PostItem/components/Header.jsx
  src/features/PostItem/components/Liked.jsx
  src/features/PostItem/components/Post.jsx
  src/features/PostItem/components/Profile.jsx
  src/features/PostItem/pages/PostItemPage.jsx
  src/pages/NewPage.jsx
Labels: ✨ Feature

#7 [refactor/calendar] 캘린더 과거 기록조회 기능 ui 구현
  src/features/MissonCalendar/assets/BookMarkIcon.png
  src/features/MissonCalendar/assets/DefaultMissionIcon.png
  src/features/MissonCalendar/assets/ModalBackIcon.png
  src/features/MissonCalendar/assets/PostImg.png
  src/features/MissonCalendar/assets/StarIcon.png
  src/features/MissonCalendar/components/Calendar.jsx
  src/features/MissonCalendar/components/CalendarModal.jsx
  src/features/MissonCalendar/components/Record.jsx
  src/pages/MissionPage.jsx
Labels: ✨ Feature

#8 [fix/calendarmodal] CalendarModal, CommentModal 수정
  src/features/MissonCalendar/components/CalendarModal.jsx
  src/features/PostItem/components/CommentListItem.jsx
  src/features/PostItem/components/CommentModalPage.jsx
  src/features/PostItem/pages/PostItemPage.jsx
  src/pages/MissionPage.jsx
Labels: 🐞 BugFix

#9 [feat/shop] shoppage 관련 컴포넌트 생성 및 TabBar 수정
  src/components/TabBar.jsx
  src/features/Shop/components/Box.jsx
  src/features/Shop/components/ShopHeader.jsx
  src/features/Shop/components/ShopList.jsx
  src/features/Shop/components/ShopListItem.jsx
  src/pages/ShopPage.jsx
Labels: 🔨 Refactor

#15 [feat/community-retrieve] 커뮤니티 api 연동코드 작성 완료
  .gitignore
  package.json
  src/Router.jsx
  src/features/Post/components/Nocation.jsx
  src/features/Post/components/PostList.jsx
  src/features/Post/components/PostListItem.jsx
  src/features/PostItem/components/CommentInput.jsx
  src/features/PostItem/components/CommentList.jsx
  src/features/PostItem/components/CommentListItem.jsx
  src/features/PostItem/components/CommentModalPage.jsx
  src/features/PostItem/components/Liked.jsx
  src/features/PostItem/components/Post.jsx
  src/features/PostItem/components/Profile.jsx
  src/features/PostItem/pages/PostItemPage.jsx
  src/mocks/comment.js
  src/mocks/comments.js
  src/mocks/community.js
  src/mocks/post.js
  src/pages/CommunityPage.jsx
  yarn.lock
Labels: ✨ Feature

#18 [design/missionUI] 미션 기능 사진 첨부시 예시 사진 추가
  src/features/Mission/Mission.jsx
  src/features/Mission/assets/ExampleImg.png
Labels: 🎨 Html&css

#28 [fix/commentbug] 게시판 댓글 수정 삭제 오류 해결
  src/features/PostItem/components/CommentInput.jsx
  src/features/PostItem/components/CommentModalPage.jsx
  src/features/PostItem/pages/PostItemPage.jsx
Labels: 🐞 BugFix

#29 [refactor/style-err-modal] 홈화면 모달 스타일링 수정
  src/features/Home/components/InfoModal.jsx
  src/features/Home/components/Profile.jsx
  src/features/Post/components/Location.jsx
  src/features/PostItem/components/CommentListItem.jsx
  src/features/PostItem/components/CommentModalPage.jsx
  src/pages/MainPage.jsx
  src/pages/MissionCalendarPage.jsx
Labels: 🎨 Html&css

#30 [refactor/darkmode] index.html 에 다크모드 지원 설정 및 브라우저명 설정
  index.html
  src/features/PostItem/components/CommentInput.jsx
Labels: 🔨 Refactor

#32 [design/tabbarIcon] 탭바 상점 아이콘 수정
  src/assets/PurpleShopIcon.png
  src/assets/ShopIcon.png
Labels: 🎨 Html&css

#34 [design/missionPage] 미션페이지 디자인 수정
  src/components/CommonComponents.jsx
  src/features/Mission/assets/ExampleImg.png
  src/features/Mission/components/ModalMission.jsx
  src/features/Mission/components/ProofMission.jsx
  src/features/Mission/components/TodayMission.jsx
Labels: 🎨 Html&css
